services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=employee'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8081
