###
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "firstName": "ibrahim",
  "lastName": "Othmani",
  "email": "yass@gmail.com"
}


###
GET http://localhost:8080/api/employees/1


###
GET http://localhost:8080/api/employees


###
PUT http://localhost:8080/api/employees/1

###
DELETE http://localhost:8080/api/employees/1